[project]
name = "natural-selection"
version = "1.0.1"
description = "Natural Selection Simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pygame>=2.6.1",
    "scipy>=1.15.2",
]
