import pygame

FRAME_RATE = 120

BOT_SPEED = 150
BOT_RANGE = 200
BOT_IMAGE = pygame.image.load("./assets/bot.png")
BOT_SIZE = 30
BOT_MIN_SPEED = 0.5
BOT_MAX_SPEED = 4
BOT_MIN_SIZE = 0.5
BOT_MAX_SIZE = 4

FOOD_IMAGE = pygame.image.load("./assets/food.png")
FOOD_SIZE = 20
FOOD_COOLDOWN = 0.15
FOOD_START = 30

MAX_ENERGY = 1200
FOOD_ENERGY = 300
BOT_ENERGY = 400
REPRODUCTION_COST = 400
REPRODUCTION_MINIMUM = 1180
MIN_SIZE_DIFF = 1.1
